name: Melenapp CI/CD - Brazil

on:
  push:
    branches:
      - main-br
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main-br

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest' # Specify Node.js version 20

      - name: Install dependencies
        run: npm install
        working-directory: melenapp-ui 

      - name: Build the app
        run: npm run build
        working-directory: melenapp-ui  
        
      - name: Build And Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_FLOWER_056905A0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./melenapp-ui" # App source code path
          # api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
